export const APP_NAME = 'SDKWork IDE';
export const APP_VERSION = '1.0.0';

export * from './hooks/useDebounce';
export * from './hooks/useWorkspaces';
export * from './hooks/useProjects';
export * from './hooks/useFileSystem';
export * from './hooks/useThreadActions';
export * from './context/AuthContext';
export * from './context/IDEContext';
export * from './contexts/ToastProvider';
export * from './services/interfaces/IWorkspaceService';
export * from './services/interfaces/IProjectService';
export * from './services/interfaces/IFileSystemService';
export * from './services/interfaces/IAuthService';
export * from './services/impl/MockWorkspaceService';
export * from './services/impl/MockProjectService';
export * from './services/impl/MockFileSystemService';
export * from './services/impl/MockAuthService';
export * from './utils/EventBus';
export * from './utils/fileSystem';
export { default as i18n } from './i18n';
